version: "3"

services:

  vote:  
    image: localhost:5050/votingdemo-vote:cockroach
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: localhost:5050/votingdemo-result:cockroach
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: localhost:5050/votingdemo-worker:cockroach
    build:
      context: ./worker
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: